/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   message_request__init
                     (MessageRequest         *message)
{
  static const MessageRequest init_value = MESSAGE_REQUEST__INIT;
  *message = init_value;
}
size_t message_request__get_packed_size
                     (const MessageRequest *message)
{
  assert(message->base.descriptor == &message_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_request__pack
                     (const MessageRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_request__pack_to_buffer
                     (const MessageRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageRequest *
       message_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageRequest *)
     protobuf_c_message_unpack (&message_request__descriptor,
                                allocator, len, data);
}
void   message_request__free_unpacked
                     (MessageRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_response__init
                     (MessageResponse         *message)
{
  static const MessageResponse init_value = MESSAGE_RESPONSE__INIT;
  *message = init_value;
}
size_t message_response__get_packed_size
                     (const MessageResponse *message)
{
  assert(message->base.descriptor == &message_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_response__pack
                     (const MessageResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_response__pack_to_buffer
                     (const MessageResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageResponse *
       message_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageResponse *)
     protobuf_c_message_unpack (&message_response__descriptor,
                                allocator, len, data);
}
void   message_response__free_unpacked
                     (MessageResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message_request__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageRequest, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MessageRequest, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MessageRequest, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionid",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageRequest, actionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_request__field_indices_by_name[] = {
  4,   /* field[4] = actionid */
  3,   /* field[3] = content */
  0,   /* field[0] = id */
  2,   /* field[2] = len */
  1,   /* field[1] = sender */
};
static const ProtobufCIntRange message_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor message_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message_request",
  "MessageRequest",
  "MessageRequest",
  "",
  sizeof(MessageRequest),
  5,
  message_request__field_descriptors,
  message_request__field_indices_by_name,
  1,  message_request__number_ranges,
  (ProtobufCMessageInit) message_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiver",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageResponse, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status_code",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageResponse, status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageResponse, error_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_response__field_indices_by_name[] = {
  3,   /* field[3] = error_message */
  0,   /* field[0] = id */
  1,   /* field[1] = receiver */
  2,   /* field[2] = status_code */
};
static const ProtobufCIntRange message_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor message_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message_response",
  "MessageResponse",
  "MessageResponse",
  "",
  sizeof(MessageResponse),
  4,
  message_response__field_descriptors,
  message_response__field_indices_by_name,
  1,  message_response__number_ranges,
  (ProtobufCMessageInit) message_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
