# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"]\n\x0fMessage_request\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06sender\x18\x02 \x02(\t\x12\x0b\n\x03len\x18\x03 \x02(\r\x12\x0f\n\x07\x63ontent\x18\x04 \x02(\x0c\x12\x10\n\x08\x61\x63tionid\x18\x05 \x02(\x05\"\\\n\x10Message_response\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08receiver\x18\x02 \x02(\t\x12\x13\n\x0bstatus_code\x18\x03 \x02(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t')
)




_MESSAGE_REQUEST = _descriptor.Descriptor(
  name='Message_request',
  full_name='Message_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Message_request.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='Message_request.sender', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='Message_request.len', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Message_request.content', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionid', full_name='Message_request.actionid', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=110,
)


_MESSAGE_RESPONSE = _descriptor.Descriptor(
  name='Message_response',
  full_name='Message_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Message_response.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='Message_response.receiver', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Message_response.status_code', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='Message_response.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['Message_request'] = _MESSAGE_REQUEST
DESCRIPTOR.message_types_by_name['Message_response'] = _MESSAGE_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_request = _reflection.GeneratedProtocolMessageType('Message_request', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_REQUEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message_request)
  ))
_sym_db.RegisterMessage(Message_request)

Message_response = _reflection.GeneratedProtocolMessageType('Message_response', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_RESPONSE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message_response)
  ))
_sym_db.RegisterMessage(Message_response)


# @@protoc_insertion_point(module_scope)
